name: win-python-build

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        arch: [x64] #, arm64]

    concurrency:
        group: ${{ github.ref }}-${{ github.base_ref }}-${{ github.head_ref }}-Windows-python-${{ matrix.os }}-${{ matrix.arch }}
        cancel-in-progress: true    
    
    steps:
    - uses: actions/checkout@v4

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: 2.9.8
        actions-cache-folder: '.xmake-cache'
        actions-cache-key: 'windows'
   
    - name: configure
      shell: cmd
      run: |
        xmake f -c -k shared -y --runtimes="MD"

    - name: build
      shell: cmd
      run: |
        xmake -b core
    - name: Upload Artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: windows-binaries
        path: ./build/**/*
        
